version: "3.9"

services:
  postgresql:
    image: postgres:15.2-alpine3.17
    restart: always
    env_file:
      - .env.postgresql.local
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.21
    restart: always
    env_file:
      - .env.pgadmin.local
    ports:
      - "5050:80"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.app.local
    depends_on:
      - postgresql
    networks:
      - default

volumes:
  postgresql:
    driver: local
