version: "3.9"

services:
  postgresql:
    image: postgres:latest
    restart: always
    env_file:
      - .env.postgresql.local
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env.pgadmin.local
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgresql:
  pgadmin:
